version: '3.8'

services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow-artifacts
    command: > 
      mlflow server \
        --backend-store-uri sqlite:////mlflow/mlflow.db \
        --default-artifact-root /mlflow-artifacts \
        --host 0.0.0.0 \
        --port 5000
    volumes:
      - mlflow-db-data:/mlflow
      - mlflow-artifacts-data:/mlflow-artifacts
    networks:
      - traductor-net

  app-traductor:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - app-traductor:1.0.0
    ports:
      - "7860:7860"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - API_KEY=${API_KEY}
    depends_on:
      - mlflow-server
    networks:
      - traductor-net

volumes:
  mlflow-db-data:
  mlflow-artifacts-data:

networks:
  traductor-net:
    driver: bridge

